Document the -v option

diff --git a/linux/multi-bootreloader b/linux/multi-bootreloader
--- a/linux/multi-bootreloader
+++ b/linux/multi-bootreloader
@@ -25,7 +25,7 @@ VERSION=0.1.0
 printf "multi-bootreloader $VERSION\n\nThis program is Free Software and has NO WARRANTY.\nhttps://github.com/benlye/flash-multi/\n\n";
 
 # Prepare simple help text to display when needed
-USAGE="Usage: multi-bootreloader [options] -p [serial device]\n\nOptions:\n  -h  Print this message and exit\n  -s  Don't prompt for confirmation\n\n"
+USAGE="Usage: multi-bootreloader [options] -p [serial device]\n\nOptions:\n  -h  Print this message and exit\n  -v  Show verbose output\n  -s  Don't prompt for confirmation\n\n"
 
 # Get the command line options
 while getopts ":f:p:hv" opt; do
@@ -121,19 +121,11 @@ case $MAPLE_USB_DEVICES in
    ;;
 esac
 
-# Die if there isn't a Maple device attached
-if [[ $MAPLE_DEVICE == "Unknown" ]]
-then
-  # No Maple device - run the serial flash
-  printf "ERROR: No compatible MULTI-Module detected.\n\n"
-  exit 2
-fi
-
 # Check if port exists for Maple USB serial - there is no port needed for DFU 
 if [ $MAPLE_DEVICE == "Native" ] ; then
   # Die if a serial port wasn't specified
   if [ "x" == "x$PORT" ]; then
-    printf "ERROR: No port specified and no programmable device found!\n\n";
+    printf "ERROR: No port specified and no DFU-mode device found!\n\n";
     printf "$USAGE"
     exit 1
   fi
@@ -143,6 +135,14 @@ if [ $MAPLE_DEVICE == "Native" ] ; then
       printf "ERROR: $PORT does not exist!\n\n";
       exit 3;
   fi
+fi
+
+# Die if there isn't a Maple device attached
+if [[ $MAPLE_DEVICE == "Unknown" ]]
+then
+  # No Maple device
+  printf "ERROR: No compatible MULTI-Module detected.\n\n"
+  exit 2
 fi
 
 # Get the directory where the script is running.
